name: Build
on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest

    steps:
      # checkout to workspace
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      # Install latest CMake.
      - uses: lukka/get-cmake@latest

      # Restore from cache the previously built ports. If "cache miss", then provision vcpkg, install desired ports, finally cache everything for the next run.
      - name: Restore from cache and run vcpkg
        uses: lukka/run-vcpkg@v4
        env: 
          vcpkgResponseFile: '${{github.workspace}}/response_file.txt'
        with:
          # Response file stored in source control, it provides the list of ports and triplet(s).
          vcpkgArguments: '@${{ env.vcpkgResponseFile }}'
          # Location of the vcpkg as submodule of the repository.
          vcpkgDirectory: '${{ github.workspace }}/submodules/vcpkg'
          # Since the cache must be invalidated when content of the response file changes, let's
          # compute its hash and append this to the computed cache's key.
          appendedCacheKey: ${{ hashFiles(env.vcpkgResponseFile) }}

      - name: 'Build with CMake and Ninja'
        uses: lukka/run-cmake@v3
        with:
          cmakeListsOrSettingsJson: CMakeListsTxtAdvanced
          cmakeListsTxtPath: '${{ github.workspace }}/CMakeLists.txt'
          useVcpkgToolchainFile: true
          buildDirectory: '${{ runner.workspace }}/b/ninja'
          cmakeAppendedArgs: '-DCMAKE_BUILD_TYPE=Release -GNinja'
